// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUKFm97Y0mRapjFv5cj1J4JLMdBgSUmiM',
    appId: '1:546093429070:android:e597984b2a6783a31d2e1f',
    messagingSenderId: '546093429070',
    projectId: 'goicro-c5e26',
    storageBucket: 'goicro-c5e26.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnhj5jlLvBVGjI1gl6zM0lOuYgXYbddMM',
    appId: '1:546093429070:ios:eab462b110414a7e1d2e1f',
    messagingSenderId: '546093429070',
    projectId: 'goicro-c5e26',
    storageBucket: 'goicro-c5e26.firebasestorage.app',
    iosClientId: '546093429070-klq13n5anjmrd6b231h26ls0qn89dvdi.apps.googleusercontent.com',
    iosBundleId: 'dev.vlab.com.localCoin',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_1y9GmEftDW7CLO4H-7p6WEnn3i4GEOI',
    appId: '1:546093429070:web:f3146da4913b5f891d2e1f',
    messagingSenderId: '546093429070',
    projectId: 'goicro-c5e26',
    authDomain: 'goicro-c5e26.firebaseapp.com',
    storageBucket: 'goicro-c5e26.firebasestorage.app',
    measurementId: 'G-7F7VBVJPM5',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCnhj5jlLvBVGjI1gl6zM0lOuYgXYbddMM',
    appId: '1:546093429070:ios:0169dc392c166a621d2e1f',
    messagingSenderId: '546093429070',
    projectId: 'goicro-c5e26',
    storageBucket: 'goicro-c5e26.firebasestorage.app',
    iosClientId: '546093429070-jptg9do2oqalor4eqfhr3odhelmpl0rn.apps.googleusercontent.com',
    iosBundleId: 'com.example.localCoin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD_1y9GmEftDW7CLO4H-7p6WEnn3i4GEOI',
    appId: '1:546093429070:web:f3146da4913b5f891d2e1f',
    messagingSenderId: '546093429070',
    projectId: 'goicro-c5e26',
    authDomain: 'goicro-c5e26.firebaseapp.com',
    storageBucket: 'goicro-c5e26.firebasestorage.app',
    measurementId: 'G-7F7VBVJPM5',
  );

}